/**
 * AIRE Product Analyst Agent
 *
 * Extracts product flows and requirement specifications from raw evidence.
 * Hydrates ProductFlowSpec[] and RequirementSpec[] into the Analysis IR.
 * Produces docs/product-spec.md as a human-readable projection.
 */

import type {
  RawEvidence,
  ProductFlowSpec,
  RequirementSpec,
  PrdSectionEvidence,
} from './types.ts';

export interface ProductAnalysisResult {
  flows: ProductFlowSpec[];
  requirements: RequirementSpec[];
  markdownProjection: string;
}

export class ProductAnalyst {
  /**
   * Analyze raw evidence and hydrate product flows and requirements.
   */
  async analyze(appName: string, evidence: RawEvidence): Promise<ProductAnalysisResult> {
    const flows: ProductFlowSpec[] = [];
    const requirements: RequirementSpec[] = [];

    // 1. Extract from PRD sections if available
    if (evidence.prdSections.length > 0) {
      for (const section of evidence.prdSections) {
        requirements.push({
          id: `req.${section.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`,
          title: section.title,
          category: 'functional',
          acceptanceCriteria: section.content
            ? section.content.split('\n').filter((l) => l.trim().length > 0).slice(0, 3)
            : [`Fulfill ${section.title} requirements`],
        });

        for (const sub of section.subsections) {
          flows.push({
            id: `flow.${sub.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`,
            name: sub.title,
            description: sub.content.trim() || `User flow for ${sub.title}`,
            steps: [
              {
                stepNumber: 1,
                screenId: 'screen.main',
                action: 'Navigate to view',
                expectedState: `${sub.title} visible`,
              },
            ],
          });
        }
      }
    }

    // 2. If no PRD sections, deduce from images
    if (flows.length === 0) {
      flows.push({
        id: 'flow.main_view',
        name: `Launch ${appName}`,
        description: `Launch ${appName} and render primary experience`,
        steps: [
          {
            stepNumber: 1,
            screenId: 'screen.main',
            action: 'Launch application',
            expectedState: 'Primary screen rendered cleanly',
          },
        ],
      });
    }

    if (requirements.length === 0) {
      requirements.push({
        id: 'req.core_experience',
        title: `${appName} Core View & Model`,
        category: 'ui',
        acceptanceCriteria: [
          'App launches cleanly without runtime exceptions',
          'Primary UI elements match design specifications',
        ],
      });
    }

    const markdownProjection = this.renderMarkdown(appName, flows, requirements);

    return {
      flows,
      requirements,
      markdownProjection,
    };
  }

  private renderMarkdown(
    appName: string,
    flows: ProductFlowSpec[],
    requirements: RequirementSpec[]
  ): string {
    const lines: string[] = [
      `# Product Specification: ${appName}`,
      '',
      '> Auto-generated by AIRE Product Analyst from Raw Evidence.',
      '',
      '## 1. Product Flows',
      '',
    ];

    for (const flow of flows) {
      lines.push(`### ${flow.name} (\`${flow.id}\`)`);
      lines.push(`${flow.description}`);
      lines.push('');
      lines.push('| Step | Screen | Action | Expected State |');
      lines.push('|---|---|---|---|');
      for (const s of flow.steps) {
        lines.push(`| ${s.stepNumber} | \`${s.screenId}\` | ${s.action} | ${s.expectedState} |`);
      }
      lines.push('');
    }

    lines.push('## 2. Requirements Matrix');
    lines.push('');
    for (const req of requirements) {
      lines.push(`### ${req.title} (\`${req.id}\`) - [${req.category.toUpperCase()}]`);
      for (const crit of req.acceptanceCriteria) {
        lines.push(`- [ ] ${crit}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
